import { create } from "zustand";
import { axiosInstance } from "../lib/axios.js";
import toast from "react-hot-toast";
const BASE_URL =
  import.meta.env.MODE && import.meta.env.MODE === "development"
    ? "http://localhost:5004"
    : "/";

export const useTestStore = create((set, get) => ({
  testIndex: null,
  roundIndex: null,
  roundType: null,
  questions: null,
  answers: null,
  score: null,
  feedback: null,
  evaluate: async (data) => {
    try {
      const res = await axiosInstance.post("/tests/evaluate-test", data);
      console.log(res);
    } catch (error) {
      console.log(error);
    }
  },

  transcribeAudio: async (formData) => {
    try {
      // This sends the .wav file to your backend ai routes
      const res = await axiosInstance.post("/ai/transcribe", formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      
      // Return the text generated by the AI
      return res.data.transcript; 
    } catch (error) {
      console.error("Transcription Store Error:", error);
      throw error;
    }
  },

  evaluateTelephonic: async (data) => {
    try {
      const res = await axiosInstance.post("/ai/evaluate-telephonic", data);
      return res.data;
    } catch (error) {
      console.error("Evaluation Store Error:", error);
      throw error;
    }
  },
  
}));